name: Task1

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Workflow_Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: My Workflow
          token: ${{ secrets.PERSONAL_TOKEN }}    
          
    name: List S3 Contents - Multi OS

  AWS-Config:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      

