name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Secret Name
        required: true
      Key:
        required: true
      Value:
        required: true
jobs:

  Task1:
    runs-on: [ ubuntu-latest]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          role-skip-session-tagging: true

      - name: AWS SecretsManager
        run: |
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN}}"
          aws secretsmanager create-secret --name ${{ github.event.inputs.Name}} --secret-string "{"Key":"${{ github.event.inputs.Key}}", "Value":"${{ github.event.inputs.Value}}"}"        
