name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Secret Name
        required: true
      Key:
        required: true
      Value:
        required: true
jobs:
  
  Task1:
    runs-on: [ ubuntu-latest]
    steps:

      - name: Workflow_Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: My Workflow
          token: "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" 
  
  Task2:
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: AWS SecretsManager
        run: |
          aws secretsmanager create-secret --name MySecret --secret-string "{"user":"Girish", "password":"Girish123"}"        
